### ISSUE TITLE
Broken go get for Go < 1.13

### ISSUE THREAD

**Issue by nordicdyno** [koenbollen/jl#16]
command:
> go get -u github.com/koenbollen/jl

produces error:
> ./cli.go:54:20: undefined: docopt
> note: module requires Go 1.13

**Comment by nordicdyno** [comment]
My proposal is don't fix docopt dependency issue, but use more popular CLI library, written in go way, without lot of magic, but handy, like viper/cobra (this pair are really popular). I could implement it on this weekend. What do you think?

**Comment by koenbollen** [comment]
Hey @nordicdyno,
Thanks for bringing this to my attention! 👌 
I'll try and find the time to get this tool to work on earlier versions of Go. For now I recommend installing `jl` using homebrew (or a released binary if you not on OSX).
I feel very little people will use this code as a dependency in a project.

As for using viper/corbra. I'm familiar with those tools (used it [here](https://github.com/koenbollen/pubsubcat)) and I do prefer to use [docopt](http://docopt.org/). Especially because it might be easier to use for people not coming from a Go background (although I do recognize that [cobra](https://github.com/spf13/cobra) is way more populair in Go land).

Is using a pre-built binary an option for you?

**Comment by koenbollen** [comment]
Could you share how to reproduce this error?

This seems to work just fine:
```bash
$ docker run -it --rm golang:1.12.9
root@7bc919530726:/go# go get -u github.com/koenbollen/jl
root@7bc919530726:/go# echo '{"msg": "Hi", "works": true}' | jl
Hi [works=true]
```

**Comment by nordicdyno** [comment]
Yeah, you're right! I had troubles on MacOS with Go 1.12, but since then I've upgraded to 1.13. And I can't reproduce error with docker, so I close issue.

P.S.

I've tried add option to `jl` and failed, `docopt` looks too magical to me and not Go-ish. But it's up to you that to choose.

**Comment by koenbollen** [comment]
Glad that the issue is resolved.

And _docopt_ is suppose to be easier to use. 😅 Just add the option to the docstring and Go! Check their vid on http://docopt.org/, you might like it (although it uses Python as an example). Thanks for the feedback!
